apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-service
  name: app-service
spec:
  type: NodePort
  ports:
  - name: "8000"
    port: 8000
    targetPort: 80000
  selector:
    app: app
status:
  loadBalancer: {}
