apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      containers:
      - image: rheamer/morgage:lts
        name: app
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always

status: {}
