version: '3.7'

x-app_environment: &app_environment
  environment:
    - DEBUG=True
    - POSTGRES_PASSWORD=postgres

services:
  back:
    image: back
    restart: unless-stopped
    volumes:
      - ./back/:/app/:cached
      - static:/app/static/:delegated
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - 8000:8000
    build:
      context: ./back
    <<: *app_environment

  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 15202:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
    <<: *app_environment

volumes:
  static:
  postgresdata:
